name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Oracle Cloud
      run: |
        ssh -o StrictHostKeyChecking=no opc@141.145.209.102 << 'EOF'
          set -e
          cd obababot
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pm2 reload ecosystem.config.js --only obababot || pm2 start ecosystem.config.js --only obababot
        EOF
